name: Full Flutter CI

on:
  workflow_dispatch:
    inputs:
      windows:
        description: "Build Windows"
        type: boolean
        default: true
      macos:
        description: "Build macOS"
        type: boolean
        default: true
      linux:
        description: "Build Linux"
        type: boolean
        default: true
      android:
        description: "Build Android"
        type: boolean
        default: true
      ios:
        description: "Build iOS"
        type: boolean
        default: true

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false
      windows: ${{ inputs.windows }}
      macos: ${{ inputs.macos }}
      linux: ${{ inputs.linux }}
      android: ${{ inputs.android }}
      ios: ${{ inputs.ios }}
